version: '3.3'
services:
  encoder:
    restart: always
    build:
      context: ./encoder
      dockerfile: dockerfile
    deploy:
      replicas: 1
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "9800:80"
    depends_on:
      - encoder
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - 30659:27017
    volumes:
      - word_exchange_db:/data/db

volumes:
  word_exchange_db:
