version: '3.3'
name: 'dev'
services:
  encoder:
    restart: always
    ports:
      - 5001:5000
    build:
      context: ./encoder
      dockerfile: dockerfile
    deploy:
      replicas: 1
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - 30659:27017
    volumes:
      - word_exchange_db:/data/db
volumes:
  word_exchange_db:
