version: '3.3'
services:
  encoder:
    restart: always
    build:
      context: ./encoder
      dockerfile: dockerfile
    deploy:
      replicas: 1
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"
    depends_on:
      - encoder
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - 30659:27017
    volumes:
      - word_exchange_db:/data/db
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: dockerfile
volumes:
  word_exchange_db:
